# Generated by Django 4.2.6 on 2023-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('mensagem', models.TextField(max_length=250)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='MeContrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=45)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ofertas de contrato',
                'verbose_name_plural': 'Ofertas de contrato',
            },
        ),
    ]
